amazon = [1, 2, 3, 4, 5, 3]
new_amazon = amazon.append(12)
new_amazon1 = amazon.insert(0, 20)
new_amazon2 = amazon.extend([23, 12, 34])
# new_amazon3 = amazon.clear()
new_amazon3 = amazon.pop(3)
new_amazon4 = amazon.index(20)
# new_amazon5 = amazon.reverse()
new_amazon5 = amazon.__len__()
# new_amazon6 = amazon.sort()
new_amazon6 = sorted(amazon)
new_amazon7 = amazon.copy()
print(amazon)
print(new_amazon1)
print(new_amazon2)
# print(new_amazon3)
print(new_amazon3)
print(new_amazon4)
# print(new_amazon5)
print(new_amazon5)
# print(new_amazon6)
print(new_amazon6)
print(new_amazon7)

# ls = list((range('a', 'z')))
# str = '@'
# ls1 = str.join(ls)
# print(ls1)
